### ISSUE TITLE
Documentation in English

### ISSUE THREAD

**Issue by MarioRicalde** [yonchu/accelerated-smooth-scroll#1]
Yonchu,

First of all kudos for your amazing work with this plugin. It definitely beats the other implementations by far!

I'm wondering if there's any chance we can translate the documentation into english? (or at least provide both translations together).

Thanks.

**Comment by yonchu** [comment]
Tried to translate README into English on trial. :worried:

**Comment by MarioRicalde** [comment]
All good. If there's something I can do, let me know. Great job!

**Comment by yonchu** [comment]
I've created the english help document.
Please feel free to point it out if there are any mistakes and improvements. :)
