### ISSUE TITLE
Error detected after installing by Vundle

### ISSUE THREAD

**Issue by marslo** [yonchu/accelerated-smooth-scroll#11]
I've add the plugin as the same as your [Readme](https://github.com/yonchu/accelerated-smooth-scroll#installation):

<pre><code>Bundle 'yonchu/accelerated-smooth-scroll'
</code></pre>

And the Error shows:
![7 4 324](https://cloud.githubusercontent.com/assets/5822057/3369874/283fc556-fb87-11e3-8627-0af978c3c2bb.png)

---

The error shows in both `GVim 7.4.324` in **Windows 7** and `Vim 7.4.324` in **Ubuntu Server 14.04 LTS**

**Comment by yonchu** [comment]
This issue is the same as #10.
