### ISSUE TITLE
Compatibility with Visual Mode

### ISSUE THREAD

**Issue by MarioRicalde** [yonchu/accelerated-smooth-scroll#2]
Is there any possible way to implement this plugin for `visual` as well? Or it's just impossible?

I've never seen anyone try this before.

**Comment by yonchu** [comment]
Hi.

Tried to implement this feature.:smile:

Note:
You need to set the following in your .vimrc to fix the cursor position.
(If not set, could not fix the cursor position but it work with smooth scroll.)

``` vim
set lazyredraw
```

If disable this feature, set the following.

``` vim
let g:ac_smooth_scroll_visualmode_key_mappings = 0
```

Thank you.

**Comment by MarioRicalde** [comment]
Yonchu,

Thank you very much for implementing this!!!

This is wonderful, I love it!

It's perfect!

Kudos!
