### ISSUE TITLE
Smooth Scroll Speed & myusuf3/numbers.vim

### ISSUE THREAD

**Issue by MarioRicalde** [yonchu/accelerated-smooth-scroll#3]
Yonchu,

I've been using accelerated-smooth-scroll, and so far it's great. 

I noticed that it's by far, the best to use MacVim when using it, since the rendering speeds are much quicker with it. However, when using [myusuf3/numbers.vim](http://github.com/myusuf3/numbers.vim), the render speed decreases a lot.

I'm thinking that using `:NumbersToggle` is the function that we need, disable the Relative Numbers when the animation begins, and enable it it back when the animation is complete.

Can you test it out and give me your thoughts? :)

**Comment by yonchu** [comment]
Hi.

I have used myusuf3/numbers.vim for the first time.
But I didn't feel like much the render speed decreases with my Vim.
It may depend on the machine specs.

I think there is the person wanting a solution for this issue.
So, I have implemented autocmd events when enter/leave smooth scroll.

Could you try the following settings and let me know the result?

``` vim
autocmd User AcSmoothScrollEnter NumbersToggle
autocmd User AcSmoothScrollLeave NumbersToggle
```

**Comment by MarioRicalde** [comment]
Yonchu,

Great! That's exactly what I was looking for. It works perfectly. 

In my case the issue comes from having 2 27'' displays and having VIM on Full Screen, when scrolling the render speed decreases. 

ありがとう！

**Comment by yonchu** [comment]
どういたしまして！:smile:
