### ISSUE TITLE
日本語ヘルプファイルでhelptagsを作ろうとするとエラーが出る。

### ISSUE THREAD

**Issue by LeafCage** [yonchu/accelerated-smooth-scroll#7]
日本語ヘルプファイルの第一行目（プラグインの説明を書く部分）に、マルチバイト文字を含めないと日本語のヘルプであると解釈されません。
たとえばこのように書きます。

```
*accelerated-smooth-scroll.jax*    加速するスムーズなスクロールを提供するプラグイン
```

**Comment by zeero** [comment]
同じ事象が発生してました。
NeoBundleInstallで他のプラグインのヘルプタグ生成まで失敗してしまう？みたいなので直して頂けると嬉しいです。

**Comment by yonchu** [comment]
ご指摘ありがとうございます。
修正しました。
